var GAME_LEVELS = [
   
  ["xx                                                                          xxx",
   "xx                                                                          xxx",
   "xx                                                                          xxx",
   "xx                                                                          xxx",
   "xx                                                                          xxx",
   "xx                                                                          xxx",
   "xx                                                 o    xx                  xxx",
   "xx                                           p     xx            x  o  x    xxx",
   "xx                                           xx                  x  o  x    xxx",
   "xx                                 t         vv                  xx o xx    xxx",
   "xx                                xxxxx          x                xvx       xxx",
   "xx                          o                                     x       xxxxx",
   "xx                   p                                            x         xxx",
   "xx                  xxxx                          xx                   x    xxx",
   "xx              xxxx                    xxxxx                             o xxx",
   "xx          xxxx!!  o                                             x         xxx",
   "xx  @       x!!!!!o   o                       o    t             xxxxx t xddxxx",
   "xxxxxxxxx  xx!!!!!xxxxxxxxxxxx   xxxx  xxxx  xx   xxx     xxxxxxx   xxxxxxxxxxx",
   "!!!!!!!!!   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!o xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
   
  ["x                                                                                                            x",
   "x                                                                                                            x",
   "x                                                                                                            x",
   "x                                      oxddx                                                                 x",
   "x                             xxxxxxxxxxxxxx                                                                 x",
   "x                                v   v                                                                       x",
   "x         xxxxxxxxxxxxxxxxx                                                                                  x",
   "x                                                                                                            x",   
   "x     x                                                                                                      x",   
   "x                                                                                                            x",
   "x   xx    o                                                                                                  x",
   "x        xx                                                                                                  x",
   "x             xx              tt                                                                             x",
   "x                  x  xxxxxxxxxxxxxxxxxxx                                                                    x",
   "x                                          x        o         o                                              x",
   "x                                              xxxxxxxxxxxxxxxxxxxxxxx     p                                 x",
   "x                                                                       x  x=          tt          =x        x",
   "x                                                                          xxxxxxxxxxxxxxxxxxxxxxxxxx        x",
   "x                                                                               |   |   |   |   |        o  xx",
   "x                                                                                                            x",
   "x                                                                                                       xx   x",
   "x                      p                  p              o               t                           p       x",
   "x                      xxxxxxxxxxxxxxxxxxxxxxxx x  x  x  xx  x   x   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                o  x            |            x    =  =              x     |                                 x",
   "x          o   xxx                            x             =  =     x                                       x",
   "x     o   xx                                                                                                 x",
   "x    xx                                                                                                      x",
   "x                                  |                                    |                                    x",
   "x                        t                              p                                                    x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                       x",
   "x                                                   x!v!x                               x                    x",
   "x                                                    x x                                    o                x",
   "x                                                                                          xx                x",
   "x                                                                                                            x",
   "x  @                                                                                                         x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!xxxxxx!!xxxx!!xxxxxxx!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                                       |                                 |            v   x",
   "x                                                            |                        |                    x",
   "x                                                                 |             |                          x",
   "x                                                                        ttt                    p          x",
   "x        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         x",
   "x        x                     =                                        =                        x         x",
   "x        x                                                                                       xxxx      x",
   "xxx      x                                                                                       x         x",
   "x        x =             tt                  tt        =                     tt                  x         x",
   "x        x         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         x      xxxx",
   "x      xxx         x                                                                   xxx       x         x",
   "x        x         x                                                                   x         x         x",
   "x        x         x                                                                   x         xxxx      x",
   "x        x         x                                                                   x       xxx         x",
   "xxx      x         x                       o     o     o     o     o                   x         x      xxxx",
   "x        x         x      xddx          o     o     o     o     o     o                xxx       x         x",
   "x        x         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          x         x         x",
   "x        x               xvx          xvx          xvx          xvx   |            x   x       xxxxxx      x",
   "x        x                                                                             x         x       xxx",
   "x        x                                                                             x         x         x",
   "x      xxx                                                                     x       x         x        tx",
   "x        x    p                 tt           tt            tt            p  |          xxx       x      xxxx",
   "x        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         xxx       x",
   "x               |                                                                              xxx         x",
   "x                  |                                                                             xxxx      x",
   "x                      |                                     x                                   x         x",
   "x   p                            ttttt        x        =         =        =   x        p         x         x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         x",
   "x                                                                                                        xxx",
   "x                                                                                                          x",
   "x                                                                                                          x",
   "x     @                                                                                                    x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!xxxxxxxxxxx!!xxxxxxxx!!xxxxxxxxxxxx!!xxxxxxxxxxxxx!!xxxxxxxx!!xxxxxxxxxxxxx"], 
   
  ["                          ",
   "                          ",
   "                          ",
   "x x xxx x x  x   x x x   x",
   " x  x x x x  x x x x x x x",
   " x  xxx xxx  xx xx x x   x",
   "                          "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
