var GAME_LEVELS = [
 
  ["xx                                                                          xxx",
   "xx                                                                          xxx",
   "xx                                                                          xxx",
   "xx                                                                          xxx",
   "xx                                                                          xxx",
   "xx                                                                          xxx",
   "xx                                                 o    xx                  xxx",
   "xx                                                 xx            x  o  x    xxx",
   "xx                                          xx                   x  o  x    xxx",
   "xx                                 y         vv                  xx o xx    xxx",
   "xx                                xxxxx          x                xvx       xxx",
   "xx                          o                                     x       xxxxx",
   "xx                   y                                            x         xxx",
   "xx  f               xxxx                          xx                   x    xxx",
   "xx              xxxx                    xxxxx                             o xxx",
   "xx          xxxx!!  o                                             x         xxx",
   "xx  @       x!!!!!o   o                       o    t        y    xxxxx t    dxxx",
   "xxxxxxxxx  xx!!!!!xxxxxxxxxxxx   xxxx  xxxx  xx   xxx     xxxxxxx   xxxxxxxxxxx",
   "!!!!!!!!!   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!o xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["x                                                                                                            x",
   "x                                                                                                            x",
   "x                                      o  d                                                                  x",
   "x                             xxxxxxxxxxxxxx                                                                 x",
   "x                                v   v                                                                       x",
   "x         xxxxxxxxxxxxxxxxx                                                                                  x",
   "x                                                                                                            x",   
   "x                                                                                                            x",   
   "x                                                                                                            x",
   "x   xx    o                                                                                                  x",
   "x        xx                                                                                                  x",
   "x             xx                                                                                             x",
   "x                     xxxxxxxxxxxxxxxxxxx                                                                    x",
   "x                                                   o         o                                              x",
   "x                                              xxxxxxxxxxxxxxxxxxxxxxx                                       x",
   "x                                                                          x=                      =x        x",
   "x                                                                          xxxxxxxxxxxxxxxxxxxxxxxxxx        x",
   "x                                                                               |   |   |   |   |        o   x",
   "x                                                                                                       xx   x",
   "x                                                        o                                                   x",
   "x                      xxxxxxxxxxxxxxxxxxxxxxxx    x     xx     x    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                o               |            x    =  =              x     |                                 x",
   "x          o    xx                            x             =  =     x                                       x",
   "x     o   xx                                                                                                 x",
   "x    xx                                                                                                      x",
   "x                                  |                                    |                                    x",
   "x                                                                                                            x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                       x",
   "x                                                   x!v!x                               x                    x",
   "x                                                    x x                                    o                x",
   "x                                                                                          xx                x",
   "x                                                                                                            x",
   "x  @                                                                                                         x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!xxxxxx!!xxxx!!xxxxxxx!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                                       |                                 |            v   x",
   "x                                                            |                        |                    x",
   "x                                                                 |             |                          x",
   "x                                                                                                          x",
   "x        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         x",
   "x        x                     =                                        =                        x         x",
   "x        x                                                                                       xxx       x",
   "xxx      x                                                                                       x         x",
   "x        x =                                           =                                         x         x",
   "x        x         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         x       xxx",
   "x      xxx         x                                                                   xxx       x         x",
   "x        x         x                                                                   x         x         x",
   "x        x         x                                                                   x         xxx       x",
   "x        x         x                                                                   x       xxx         x",
   "xxx      x         x                       o     o     o     o     o                   x         x       xxx",
   "x        x         x       d            o     o     o     o     o     o                xxx       x         x",
   "x        x         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          x         x         x",
   "x        x               xvx          xvx          xvx          xvx   |            x   x       xxxxx       x",
   "x        x                                                                             x         x         x",
   "x        x                                                                             x         x         x",
   "x      xxx                                                                     x       x         x         x",
   "x        x                                                                  |          xxx       x       xxx",
   "x        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         x         x",
   "x               |                                                                              xxx         x",
   "x                  |                                                                             xxx       x",
   "x                      |                                     x                                   x         x",
   "x                                             x        =         =        =   x                  x         x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         x",
   "x                                                                                                        xxx",
   "x                                                                                                          x",
   "x                                                                                                          x",
   "x     @                                                                                                    x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!xxxxxxxxxxx!!xxxxxxxx!!xxxxxxxxxxxx!!xxxxxxxxxxxxx!!xxxxxxxx!!xxxxxxxxxxxxx"], 
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
